export const productValue = [
  {
    id: 0,
    name: "Mahsulot 1",
    img: "https://react-portfolio-new.netlify.app/img/guruh1.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 1,
    name: "Mahsulot 2",
    img: "https://react-portfolio-new.netlify.app/img/shop8.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 2,
    name: "Mahsulot 3",
    img: "https://react-portfolio-new.netlify.app/img/shop5.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 3,
    name: "Mahsulot 4",
    img: "https://react-portfolio-new.netlify.app/img/shop2.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 4,
    name: "Mahsulot 5",
    img: "https://react-portfolio-new.netlify.app/img/shop3.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 5,
    name: "Mahsulot 6",
    img: "https://react-portfolio-new.netlify.app/img/shop6.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 6,
    name: "Mahsulot 7",
    img: "https://react-portfolio-new.netlify.app/img/shop4.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 7,
    name: "Mahsulot 8",
    img: "https://react-portfolio-new.netlify.app/img/shop11.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 8,
    name: "Mahsulot 9",
    img: "https://react-portfolio-new.netlify.app/img/shop10.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
  {
    id: 9,
    name: "Mahsulot 10",
    img: "https://react-portfolio-new.netlify.app/img/shop7.png",
    price: 30,
    discount: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim soluta quibusdam beatae velit in nobis vitae animi impedit vel praesentium.",
  },
];
